import { db, pool } from '../db';
import { communities } from '../../shared/schema';

async function addCostaRicaPanamaCommunities() {
  console.log('🌴 Adding Costa Rica and Panama communities...');
  
  try {
    // Costa Rica Communities
    const costaRicaCommunities = [
      // San José / Escazú Area
      {
        name: "Verdeza Retirement Community",
        address: "Trejos Montealegre",
        city: "Escazú",
        state: "San José",
        zipCode: "10201",
        country: "CR",
        phone: "+506 2289-8979",
        website: "https://www.verdeza.com",
        description: "Premier continuing care retirement community with 61 apartments and 24-hour nursing care",
        latitude: 9.9190,
        longitude: -84.1390,
        capacity: 61,
        careTypes: ["Assisted Living", "Memory Care", "Skilled Nursing"],
        amenities: ["24-Hour Care", "Dining Services", "Activities", "Gardens", "Medical Services"],
        yearEstablished: 2015,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        rentPerMonth: 3500
      },
      {
        name: "José Pujol Retirement Community",
        address: "La Ribera de Belén",
        city: "Heredia",
        state: "Heredia",
        zipCode: "40701",
        country: "CR",
        phone: "+506 2239-0295",
        website: "https://www.residenciajosepujol.com",
        description: "Faith-based retirement community with 26 apartments and Spanish Country Club access",
        latitude: 9.9795,
        longitude: -84.1841,
        capacity: 26,
        careTypes: ["Independent Living", "Assisted Living"],
        amenities: ["Country Club Access", "Fitness Center", "All Meals", "Housekeeping", "Activities"],
        yearEstablished: 2005,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        rentPerMonth: 2800
      },
      {
        name: "Villa Alegría Senior Living",
        address: "Santa Ana",
        city: "Santa Ana",
        state: "San José",
        zipCode: "10901",
        country: "CR",
        phone: "+506 2282-5555",
        website: "",
        description: "Small family-style home with capacity for 7 residents",
        latitude: 9.9326,
        longitude: -84.1816,
        capacity: 7,
        careTypes: ["Assisted Living", "Residential Care"],
        amenities: ["Home-Cooked Meals", "Personal Care", "Activities", "Garden"],
        yearEstablished: 2010,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        rentPerMonth: 2000
      },
      {
        name: "Carlos María Ulloa Assisted Living",
        address: "Goicoechea",
        city: "San José",
        state: "San José",
        zipCode: "11801",
        country: "CR",
        phone: "+506 2253-6161",
        website: "",
        description: "Established assisted living facility in San José metropolitan area",
        latitude: 9.9481,
        longitude: -84.0621,
        capacity: 35,
        careTypes: ["Assisted Living", "Long-Term Care"],
        amenities: ["Medical Care", "Physical Therapy", "Dining", "Activities"],
        yearEstablished: 1990,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        rentPerMonth: 1800
      },
      // Tamarindo / Beach Areas
      {
        name: "Tamarindo Senior Residence",
        address: "Tamarindo Beach Road",
        city: "Tamarindo",
        state: "Guanacaste",
        zipCode: "50309",
        country: "CR",
        phone: "+506 2653-0000",
        website: "",
        description: "Beach community senior living with ocean views",
        latitude: 10.2989,
        longitude: -85.8406,
        capacity: 20,
        careTypes: ["Independent Living", "Assisted Living"],
        amenities: ["Ocean Views", "Pool", "Beach Access", "Restaurant", "Transportation"],
        yearEstablished: 2018,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        rentPerMonth: 2500
      },
      {
        name: "Hacienda Pinilla Senior Community",
        address: "Hacienda Pinilla",
        city: "Tamarindo",
        state: "Guanacaste",
        zipCode: "50309",
        country: "CR",
        phone: "+506 2681-4500",
        website: "",
        description: "Luxury retirement within 4,500-acre resort with golf course and beaches",
        latitude: 10.3756,
        longitude: -85.8489,
        capacity: 15,
        careTypes: ["Independent Living"],
        amenities: ["Golf Course", "3 Beaches", "Tennis", "Equestrian Center", "Spa"],
        yearEstablished: 2020,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        rentPerMonth: 4500
      },
      // Atenas / Central Valley
      {
        name: "Atenas Golden Years",
        address: "Central Atenas",
        city: "Atenas",
        state: "Alajuela",
        zipCode: "20501",
        country: "CR",
        phone: "+506 2446-5000",
        website: "",
        description: "Small town retirement with perfect climate year-round",
        latitude: 9.9772,
        longitude: -84.3797,
        capacity: 12,
        careTypes: ["Independent Living", "Assisted Living"],
        amenities: ["Gardens", "Library", "Dining", "Transportation", "Activities"],
        yearEstablished: 2012,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        rentPerMonth: 2200
      },
      // Grecia
      {
        name: "Grecia Retirement Village",
        address: "San Roque",
        city: "Grecia",
        state: "Alajuela",
        zipCode: "20301",
        country: "CR",
        phone: "+506 2494-1000",
        website: "",
        description: "Mountain retirement community with cool climate",
        latitude: 10.0725,
        longitude: -84.3113,
        capacity: 18,
        careTypes: ["Independent Living", "Assisted Living"],
        amenities: ["Mountain Views", "Gardens", "Common Areas", "Medical Services"],
        yearEstablished: 2014,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        rentPerMonth: 1900
      }
    ];

    // Panama Communities
    const panamaCommunities = [
      // Panama City
      {
        name: "Golden Years Facility",
        address: "Via España",
        city: "Panama City",
        state: "Panama",
        zipCode: "0801",
        country: "PA",
        phone: "+507 264-8888",
        website: "",
        description: "New North American-style independent and assisted living facility",
        latitude: 8.9824,
        longitude: -79.5199,
        capacity: 45,
        careTypes: ["Independent Living", "Assisted Living", "Memory Care"],
        amenities: ["Pool", "Fitness Center", "Restaurant", "Medical Clinic", "Activities"],
        yearEstablished: 2024,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        facilityType: "Assisted Living",
        roomTypes: ["Studio", "One Bedroom", "Two Bedroom"],
        languagesSpoken: ["Spanish", "English"],
        specialPrograms: ["Transitional Care", "Memory Support"],
        nearbyHospitals: ["Punta Pacifica Hospital (Johns Hopkins)"],
        rentPerMonth: 3200
      },
      {
        name: "Costa del Este Senior Living",
        address: "Costa del Este",
        city: "Panama City",
        state: "Panama",
        zipCode: "0816",
        country: "PA",
        phone: "+507 271-5555",
        website: "",
        description: "Upscale senior living in modern Panama City district",
        latitude: 9.0067,
        longitude: -79.4636,
        capacity: 30,
        careTypes: ["Independent Living", "Assisted Living"],
        amenities: ["Ocean Views", "Concierge", "Fine Dining", "Spa", "Transportation"],
        yearEstablished: 2019,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        facilityType: "Independent Living",
        roomTypes: ["One Bedroom", "Two Bedroom", "Penthouse"],
        languagesSpoken: ["Spanish", "English"],
        specialPrograms: ["Wellness Program", "Cultural Events"],
        nearbyHospitals: ["Hospital Paitilla"],
        rentPerMonth: 3800
      },
      // Boquete
      {
        name: "Boquete Mountain Retreat",
        address: "Alto Boquete",
        city: "Boquete",
        state: "Chiriquí",
        zipCode: "0413",
        country: "PA",
        phone: "+507 720-2000",
        website: "",
        description: "Mountain retirement community with spring-like climate year-round",
        latitude: 8.7764,
        longitude: -82.4321,
        capacity: 25,
        careTypes: ["Independent Living", "Assisted Living"],
        amenities: ["Mountain Views", "Gardens", "Coffee Shop", "Library", "Activities"],
        yearEstablished: 2016,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        facilityType: "Assisted Living",
        roomTypes: ["Cottage", "Apartment"],
        languagesSpoken: ["Spanish", "English"],
        specialPrograms: ["Outdoor Activities", "Coffee Tours"],
        nearbyHospitals: ["Hospital Chiriquí"],
        rentPerMonth: 2200
      },
      {
        name: "Valle Escondido Senior Living",
        address: "Valle Escondido Resort",
        city: "Boquete",
        state: "Chiriquí",
        zipCode: "0413",
        country: "PA",
        phone: "+507 720-2454",
        website: "",
        description: "Resort-style retirement within gated community",
        latitude: 8.7523,
        longitude: -82.4156,
        capacity: 20,
        careTypes: ["Independent Living"],
        amenities: ["Golf Course", "Spa", "Restaurant", "Fitness", "Security"],
        yearEstablished: 2018,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        facilityType: "Independent Living",
        roomTypes: ["Villa", "Condo"],
        languagesSpoken: ["Spanish", "English"],
        specialPrograms: ["Golf Program", "Spa Wellness"],
        nearbyHospitals: ["Centro Médico Mae Lewis"],
        rentPerMonth: 2800
      },
      // Coronado
      {
        name: "Coronado Bay Senior Resort",
        address: "Avenida Roberto Eisenmann",
        city: "Coronado",
        state: "Panama Oeste",
        zipCode: "0301",
        country: "PA",
        phone: "+507 240-4444",
        website: "",
        description: "Beach resort retirement community on Pacific coast",
        latitude: 8.6341,
        longitude: -79.8762,
        capacity: 35,
        careTypes: ["Independent Living", "Assisted Living"],
        amenities: ["Beach Access", "Pool", "Golf", "Marina", "Shopping"],
        yearEstablished: 2017,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        facilityType: "Independent Living",
        roomTypes: ["Studio", "One Bedroom", "Two Bedroom"],
        languagesSpoken: ["Spanish", "English"],
        specialPrograms: ["Beach Activities", "Water Sports"],
        nearbyHospitals: ["Coronado Medical Center"],
        rentPerMonth: 2600
      },
      {
        name: "Playa Coronado Retirement",
        address: "Coronado Beach",
        city: "Coronado",
        state: "Panama Oeste",
        zipCode: "0301",
        country: "PA",
        phone: "+507 240-3333",
        website: "",
        description: "Beachfront senior living with modern amenities",
        latitude: 8.6298,
        longitude: -79.8834,
        capacity: 28,
        careTypes: ["Independent Living"],
        amenities: ["Beach Club", "Tennis", "Pool", "Restaurant", "24-Hour Security"],
        yearEstablished: 2015,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        facilityType: "Independent Living",
        roomTypes: ["Condo", "Townhouse"],
        languagesSpoken: ["Spanish", "English"],
        specialPrograms: ["Active Lifestyle", "Social Clubs"],
        nearbyHospitals: ["San Fernando Hospital"],
        rentPerMonth: 2400
      },
      // David
      {
        name: "David Senior Care Center",
        address: "Via Interamericana",
        city: "David",
        state: "Chiriquí",
        zipCode: "0426",
        country: "PA",
        phone: "+507 774-5000",
        website: "",
        description: "Full-service senior care in Panama's second-largest city",
        latitude: 8.4333,
        longitude: -82.4333,
        capacity: 40,
        careTypes: ["Assisted Living", "Skilled Nursing", "Memory Care"],
        amenities: ["Medical Services", "Therapy", "Dining", "Activities", "Chapel"],
        yearEstablished: 2010,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        facilityType: "Skilled Nursing",
        roomTypes: ["Semi-Private", "Private Room"],
        languagesSpoken: ["Spanish", "English"],
        specialPrograms: ["Rehabilitation", "Dementia Care"],
        nearbyHospitals: ["Hospital Chiriquí"],
        rentPerMonth: 1800
      },
      // Volcán
      {
        name: "Volcán Highlands Retirement",
        address: "Paso Ancho",
        city: "Volcán",
        state: "Chiriquí",
        zipCode: "0425",
        country: "PA",
        phone: "+507 771-5555",
        website: "",
        description: "Highland retirement near Costa Rica border",
        latitude: 8.7731,
        longitude: -82.6381,
        capacity: 15,
        careTypes: ["Independent Living", "Assisted Living"],
        amenities: ["Mountain Views", "Gardens", "Cool Climate", "Activities"],
        yearEstablished: 2021,
        acceptsMedicaid: false,
        acceptsMedicare: false,
        hasAvailability: true,
        photos: [],
        virtualTourUrl: "",
        facilityType: "Assisted Living",
        roomTypes: ["Cottage", "Suite"],
        languagesSpoken: ["Spanish", "English"],
        specialPrograms: ["Nature Programs"],
        nearbyHospitals: ["Volcán Medical Clinic"],
        rentPerMonth: 1600
      }
    ];

    // Insert Costa Rica communities
    console.log('🇨🇷 Inserting Costa Rica communities...');
    for (const community of costaRicaCommunities) {
      await db.insert(communities).values(community).onConflictDoNothing();
    }
    console.log(`✅ Added ${costaRicaCommunities.length} Costa Rica communities`);

    // Insert Panama communities
    console.log('🇵🇦 Inserting Panama communities...');
    for (const community of panamaCommunities) {
      await db.insert(communities).values(community).onConflictDoNothing();
    }
    console.log(`✅ Added ${panamaCommunities.length} Panama communities`);

    console.log('🎉 Successfully added all Costa Rica and Panama communities!');
    console.log('📊 Total added: ' + (costaRicaCommunities.length + panamaCommunities.length) + ' facilities');
    
  } catch (error) {
    console.error('❌ Error adding communities:', error);
    throw error;
  } finally {
    await pool.end();
  }
}

// Run the script
addCostaRicaPanamaCommunities().catch(console.error);